services:
  app:
    restart: always
    image: washington1995luiz/cloudflare-service:1.0.2
    build:
      context: .
      dockerfile: Dockerfile  # Points to the Dockerfile that builds the Java app
    container_name: java-app
    env_file:
      - ".env"
    ports:
      - "8080:8080"  # Exposing the Java app's port
    depends_on:
      - rabbitmq  # Ensure RabbitMQ starts first
      - redis     # Ensure Redis starts before the app
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4.0.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network
    command: >
      sh -c "apt-get update && apt-get upgrade -y &&
      apt-get install -y wget &&
      wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.2/rabbitmq_delayed_message_exchange-4.0.2.ez -P /opt/rabbitmq/plugins &&
      rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
      rabbitmq-server"

  redis:
    image: redis:7.4.1  # Latest Redis version
    container_name: redis
    ports:
      - "6379:6379"  # Default Redis port
      - "6380:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data  # Persistent storage for Redis data

volumes:
  rabbitmq-data:
  redis-data:

networks:
  app-network:
    driver: bridge